image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: notify
tasks:
  - init: >
      (cp -n .env.example .env || true) &&
      pipenv install &&
      psql -U gitpod -c 'CREATE DATABASE example;' &&
      psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d example &&
      bash database.sh &&
      python docs/assets/greeting.py back
  - command: >
      echo BACKEND_URL=$(gp url 3001) >> .env && 
      npm install &&
      python docs/assets/greeting.py front
    openMode: split-right
  # - name: Install PostgreSQL
  #   command: |
  #     sudo apt-get update
  #     sudo apt-get install -y postgresql postgresql-contrib

vscode:
  extensions:
    - esbenp.prettier-vscode
